### ISSUE TITLE
Clarify survey dip convention

### ISSUE THREAD

**Issue by rmcaixeta** [JuliaEarth/DrillHoles.jl#10]
The keyword argument `invertdip` in `Survey` definition may cause confusion as it is. Additionally to that, `dh.trace` uses a fixed convention for internal use and it's not specified in the docstrings.

The current proposed solution is to substitute `invertdip` to `dipconvention`, which could hold the values `:positivedownwards` or `:negativedownwards`. For trace file, a simple solution is to specify the fixed convention in the docs; or adapt the dip sign to the informed convention, what would be better, but need to check how much of the code need to be adapted to it.

**Comment by juliohm** [comment]
I like the `dipconvention` keyword, it is much more explicit 👍🏽 I would maybe just use `convention` though since I don't see other type of convention possible? Or there are other annoyances in the wild? Anything else can change in drill hole files other than the dip convention?

I think the ideal behavior would be one in which users can consume a given convention and operate the data internally as if it was in the specified convention. Right now, the main confusion is caused by the fact that the internal representation is always positive upwards regardless of the option.

What about saving a convention field in the structs, and then refactor the specific functions to use this option?

**Comment by rmcaixeta** [comment]
Thanks for the suggestions. I opened the PR with that. I'll make some additional tests and merge it tomorrow if all is ok. Better merge it before your course, right @juliohm and @fnaghetini?

**Comment by juliohm** [comment]
Thanks @rmcaixeta that would be awesome. We can always pin the version to an old version if we encounter issues. I think the transition will be super smooth as we only need to update the keyword name and check the signs in the rest of the notebook 👍🏽 

One thing that could also be useful is adding back the option `invertdip` but now with a different semantics. Basically, the option `convention` specifies the input convention and the user can choose to keep working with the input convention throughout his/her workflow or choose to flip the sign after a convention is correctly specified for the input. So basically, `convention` becomes explicit and users can switch if necessary. Does it make sense?

So for example, if we get a dataset with positive dips pointing downwards, we can let DrillHoles.jl know about it with `convention = :positivedownwards` and additionally change to the other convention with `invertdip = true` if that is preferred.

**Comment by juliohm** [comment]
Or maybe another name of the option like `invert` to be consistent with the fact that only one type of convention exists as described by the `convention`.

**Comment by rmcaixeta** [comment]
Great.
Got your point. I was implementing `invert` here to check how it goes, but I felt that it was making it more confuse, as there is no explicit standard definition anymore. Besides that, I'd say that with default `convention=:auto`, the user will not have to worry about dip sign in 99% of the cases. And in that 1%, just need to choose `convention=:positivedownwards` or `convention=:negativedownwards`. I'll stick as it is for now. I just additionally adjusted the compositing zone field workflow for cases with missing values.

**Comment by juliohm** [comment]
Amazing. Thanks for the quick updates. Looking forward to trying the new
version in the notebooks.
