### ISSUE TITLE
Parameters in the collar table

### ISSUE THREAD

**Issue by a-cordeiro** [JuliaEarth/DrillHoles.jl#17]
Hello. I'd like to suggest a feature to the package. I'm using the DrillHoles.jl to a task, and I have important data on the collar table that I can't move, for logistical matters, to the interval table. When I use the drillhole function, these data are not passed to the desurveyed table generated by the drillhole function. For what I've researched, that's how it should work, given that the collar function doesn't recgonize explicitly any parameters besides x, y, z, holeid and enddepth and all the other data should be in the interval table. Is it feasible to add the option of using data that are located at the collar table and can't be moved around in the same way as the interval table?

**Comment by juliohm** [comment]
Hi @a-cordeiro , as you pointed out the collar table only contains the X,Y,Z,ID as the relevant information. Even if we wanted to copy the other columns to the final result, these final columns would be mostly filled with missing values.

Can you comment on the logistical matters? The most natural solution consists of rearranging the input tables to the standard specification, and that should be relatively easy to do with Julia's DataFrames.jl ecosystem.

Also, notice that we have fixed a couple of bugs in the #cleanup branch of this repository. We didn't have time to finish it up yet, but worth keeping it in mind.
