### ISSUE TITLE
Add warnings found during desurvey

### ISSUE THREAD

**Issue by rmcaixeta** [JuliaEarth/DrillHoles.jl#3]
Currently, only some errors are checked during desurvey
It is possible to include other warnings to the `DrillHole.warn`

e.g.
- validate last interval against collar end depth
- check duplicate hole names and inform
- hole name in survey table but not in collar table
- hole name in interval table but not in collar table
- no survey at zero depth
- duplicated survey
- single value of survey
- big deviations between adjacent survey intervals
- warn for repeated column names in different tables

**Comment by juliohm** [comment]
We can consider these and other warnings after the major refactoring in #15 . For some of them we already have fixes like for example the "single value of survey" case you listed. In this case, I am just duplicating the row for the hole id with an increased AT value. That way we can interpolate the full trace with constant AZM and DIP. This also fixes the "no survey at zero depth" case.

**Comment by juliohm** [comment]
Warnings should use the Julia logging system with @warn so that users can redirect the output to files, etc. We could also add a dependency for logging if necessary.
